---
- hosts: queenbee
  gather_facts: no
  tasks:
    - name: "Generate user key"
      register: keyResult
      user:
        name: "{{ansible_user}}"
        generate_ssh_key: yes
        ssh_key_file: .ssh/id_rsa

- hosts: es
  gather_facts: no
  tasks:
    - name: "Set authorized key took from file"
      authorized_key:
        user: "{{ansible_user}}"
        state: present
        key: "{{ hostvars['queenbee']['keyResult'].ssh_public_key }}"

- hosts: hive
  tasks:
    - name: "Add hostname to /etc/hosts"
      become: yes
      lineinfile:
        dest: "/etc/hosts"
        line: "{{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}  {{ hostvars[item]['inventory_hostname'] }}"
        state: present
      loop: "{{ groups['hive'] }}"
