---
- name: Change host name
  become: yes
  script: change-hostname.sh {{hostname}}
- name: "Set authorized key took from file"
  authorized_key:
    user: "{{user}}"
    state: present
    key: "{{ lookup('file', keyFilePath) }}"
- name: "Disable ssh password authentication"
  become: yes
  shell: sed -i "s/.*PasswordAuthentication.*/PasswordAuthentication no/g" /etc/ssh/sshd_config
- name: "Restart ssh service"
  become: yes
  shell: systemctl restart sshd.service
- name: Set proxy to root
  become: yes
  shell: |
    cp ~/.bashrc ~/.bashrc_bak    
    cat >>~/.bashrc  <<EOF
    alias proxy="
    {{proxyCommand}}"
    alias unproxy="
    {{unproxyCommand}}"
    EOF
- name: Set proxy to default user
  shell: |
    cp ~/.bashrc ~/.bashrc_bak    
    cat >>~/.bashrc  <<EOF
    alias proxy="
    {{proxyCommand}}"
    alias unproxy="
    {{unproxyCommand}}"
    EOF
- name: Update apt packages
  become: yes
  # apt:
  #   upgrade: yes
  #   update_cache: yes
  #   cache_valid_time: 86400 #One day
  shell: |
    {{proxyCommand}}
    apt-get update
# apt-get upgrade -y -qq
    {{unproxyCommand}}
- name: Install docker
  become: yes
  shell: |
    {{proxyCommand}}
    curl -sSL https://get.docker.com | sh
    usermod -aG docker {{user}}
    {{unproxyCommand}}
- name: Install docker-compose
  become: yes
  shell: |
    {{proxyCommand}}
    apt-get install libffi-dev libssl-dev python3-dev python3 python3-pip -y -qq
    pip3 install docker-compose
    {{unproxyCommand}}
- name: Set docker service proxy
  become: yes
  shell: |
    mkdir /etc/systemd/system/docker.service.d
    touch /etc/systemd/system/docker.service.d/http-proxy.conf
    cat >/etc/systemd/system/docker.service.d/http-proxy.conf <<EOF
    [Service]
    Environment="HTTP_PROXY={{proxyUrl}}" "NO_PROXY=localhost,127.0.0.0/8"
    EOF
    systemctl daemon-reload
    systemctl restart docker
# 参考 https://stackoverflow.com/a/54220188/3483986

- name: Pull elasticsearch docker images
  become: yes
  shell: |
    docker pull elasticsearch:{{elasticsearchVersion}}

